### ISSUE TITLE
Hover info need scroll feature

### ISSUE THREAD

**Issue by sinyo-matu** [kilbd/nova-rust#17]
Thank you for making this amazing extension!

If docs are super long like pic below, I can only see a part of them.
<img width="677" alt="スクリーンショット 2022-03-17 14 43 09" src="https://user-images.githubusercontent.com/3389913/158745073-079866f7-07ae-4de7-9dd1-6f6082632633.png">

maybe add a scroll feature for Hover info window like VSCode will be nice.

**Comment by kilbd** [comment]
Thanks for reaching out to let me know about an issue! Unfortunately, this isn't something I can control via the Extensions API. This behavior is determined by Nova itself, so you should submit a bug report (or feature request depending on your perspective) with the Nova Help form:

https://nova.app/help/

The more people they hear from about an issue, the more likely they are to prioritize it.
