### ISSUE TITLE
add suggestions out of scope that automatically add a use when selected

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#18]
this is the biggest reason im considering not to switch to nova, both vscode and jetbrains has this

it'd work something like
```rs
fn foo() {
  Conte| // suggestion pops up: Context - use crate::Context;
}
```
when the suggestion is selected (enter pressed), the code would now be
```rs
use crate::Context;

fn foo() {
  Context|
}
```

right now you'd have to:
1. start typing
2. realize you need to add a `use`
3. either
    4. move all the way up
    5. figure out where the item is
    6. add the use
    7. go back to where you were and continue coding
4. or
    4. finish typing the item's whole name
    5. save
    6. wait for the "add a use for this item" lint to pop up
    7. press cmd shift a to apply the suggestion
    8. save again
    9. wait for the errors to disappear
    10. continue coding

**Comment by kilbd** [comment]
Hi Lara! Wonderful to hear from you again! Thank you for continuing to find ways to make this extension better.

I'm sorry to report that I looked into this, and it's not currently possible. 😞 It's an LSP spec version 3.16 feature which isn't implemented by Nova. Based on the configuration Nova passes to Rust Analyzer, RA doesn't even try to offer these completions. I wouldn't be able to listen for them and handle requests within this extension.

These auto-import completions are implemented similarly in other language servers, and very much something others want. I bumped the [forum thread](https://devforum.nova.app/t/language-server-completionitem-additional-edit-command-support/716) to +1 the feature request. We can only hope Panic will prioritize better LSP support.
