### ISSUE TITLE
add ability to rename symbols/files

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#19]
currently we have to manually select every instance of a variable/struct/enum/function/module etc. and it gets hard, most ides have this ability under "refactor", im not sure if its provided by ra or done manually though

**Comment by kilbd** [comment]
This is a feature of RA, and one I've been meaning to implement. I'll need to implement it manually as a Nova command, so I've admittedly been putting it off. I'll make it a top priority – thanks for the nudge!
