### ISSUE TITLE
[BUG] symbols make everything is nested under the first item

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#21]
the symbols sidebar make the first item the top item

**To Reproduce**
1. add two items to the code
2. open symbols view
3. everything else is under the first item

**Expected behavior**
the items are independent from each other, each are different tops

**Screenshots**
<img width="249" alt="Screen Shot 2022-04-16 at 14 35 41" src="https://user-images.githubusercontent.com/82576556/163676953-11a8eb9d-3fb9-4724-9ce0-60afd1838bb4.png">
<img width="249" alt="Screen Shot 2022-04-16 at 14 36 21" src="https://user-images.githubusercontent.com/82576556/163676954-7f6ee31f-c6bd-4514-abaa-4cb69bc47fb1.png">

**Versions (please complete the following information):**
 - macOS: Monterey
 - Processor: M1
 - Nova 9.3
 - Extension Version 2.0.0

**Comment by kilbd** [comment]
Yeah, I've [struggled with symbols](https://devforum.nova.app/t/symbolication-of-method-implementations/1179), particularly for structs and enums. It makes sense for methods to be nested under structs and enums, but I haven't figured out how to make that happen. I kinda punted after not getting any help. I'll try to revisit it after resolving some of the other extension issues.

**Comment by laralove143** [comment]
thats not what i meant, what i mean is the first item is always seen as the top one, everything else, like structs you define after that item, are nested under it, which rust doesn't even allow!

**Comment by kilbd** [comment]
I heard back from the Nova developer, and he confirmed that my desire to nest methods under structs was the problem and is not possible with the current parser. So, I've refactored `impl` blocks to be their own symbol, like this:

<img width="198" alt="Capture of Rust symbols in Nova" src="https://user-images.githubusercontent.com/2053455/165997998-1355add8-7d54-40f8-b95f-71b51de0bace.png">

This change is in extension version 2.0.1.
