### ISSUE TITLE
[SYNTAX] const keyword in methods arent highlighted

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#23]
<img width="304" alt="Screen Shot 2022-04-16 at 17 04 35" src="https://user-images.githubusercontent.com/82576556/163677949-59565774-fc34-4c12-b42d-1c74f6ac3789.png">

**Expected behavior**
<img width="326" alt="Screen Shot 2022-04-16 at 17 07 06" src="https://user-images.githubusercontent.com/82576556/163678032-d81e8cea-6103-4a18-be8f-8aee0c3dff89.png">

**Versions (please complete the following information):**
 - macOS: Monterey
 - Processor: M1
 - Nova 9.3
 - Extension Version 2.0.0

**Comment by kilbd** [comment]
Thank you for this syntax bug report! The fix is in extension version 2.0.1.
