### ISSUE TITLE
[SYNTAX] separated literal hexes arent highlighted

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#24]
<img width="98" alt="Screen Shot 2022-04-16 at 17 12 53" src="https://user-images.githubusercontent.com/82576556/163678306-1e80025e-8f2d-43f2-a4fa-e7b444ca0a0f.png">

**Sample code**
```rust
fn foo() {
    0x00_71_ce;
    0x0071ce;
}
```

**Comment by kilbd** [comment]
Thank you for this bug report! The fix is added in extension version 2.0.1.
