### ISSUE TITLE
[SYNTAX] Tuple type annotations (?) in function signatures

### ISSUE THREAD

**Issue by belcar-s** [kilbd/nova-rust#32]
**Describe what doesn't look right**
In the example below, `u32` is colored with purple, as if it were the name of a parameter. An opening parenthesis is colored with white, instead of gray.

**Screenshots**
<img width="396" src="https://user-images.githubusercontent.com/73370025/177022578-9fd85c3f-85bf-4408-ad35-eff76af81f33.png">

**How would you expect the features to be highlighted?**
The opening parenthesis should be gray, and the second `u32` should be yellow.

**Sample code**
This is from the Rust book :=). Since its snippets are meant to demonstrate various language features, I think they could be useful for testing.

```rust
fn area(dimensions: (u32, u32)) -> u32 {
    dimensions.0 * dimensions.1
}
```

**Comment by kilbd** [comment]
Thank you for including sample code so I could test with it! This particular snippet looks correct in version 2.3.0 that I just released with Tree Sitter support.
