### ISSUE TITLE
Support Tree Sitter in Nova 10

### ISSUE THREAD

**Issue by cjwcommuny** [kilbd/nova-rust#35]
Nova 10 (expected to released soon) supports Tree Sitter, which enables more accurate syntax highlighting. It would be great to support it.

**Comment by kilbd** [comment]
Yes, I'm excited about it too! Using the Tree Sitter parser from the community will be far superior to my attempt at a grammar. Beta 4 seems to have resolved the crashers I was experiencing from the compiled library, so I should be able to dig into writing queries to connect to Nova features.

**Comment by haze** [comment]
I know it's only been 23 days and not your full time job, but are there any updates on this front?

**Comment by kilbd** [comment]
My thanks to you and everyone else for your patience. I am indeed juggling many life things, but have made some progress on this feature. I have a first pass on syntax highlighting but am currently a bit [hung up on symbols](https://devforum.nova.app/t/scheme-help-with-tree-sitter-symbol-queries/1826) – which [has happened before](https://devforum.nova.app/t/symbolication-of-method-implementations/1179). If forum help isn't forthcoming, I may punt on nicely organized symbols for now.

**Comment by 143mailliw** [comment]
Any updates on this?

**Comment by kilbd** [comment]
Good timing, as I just recently picked this up again. I got a new job late last year (with an all-Windows shop 😭) so I had to put this down and haven't been in Nova for a while. Things are starting to settle so I have some time and head space to poke at this some more.

**Comment by kilbd** [comment]
I just pushed out a new version (2.3.0) using Tree Sitter. If you're still using this extension, I appreciate your patience. Please open a new issue if you have any suggestions or experience any problems with highlights and symbols!
