### ISSUE TITLE
Renaming to Rust Analyzer

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#4]
I personally never knew this existed. There’s already an extension for RLS, I think it’d be clearer if it was named to Rust Analyzer everywhere

**Comment by kilbd** [comment]
Hi Lara! Great to hear from you so soon!

My goal for this extension is to provide more extensive support for the Rust language than connecting to Rust Analyzer, including syntax definitions, format on save, and possibly commands. Also, learning a lesson from RLS losing favor to Rust Analyzer, I don't want to tie the extension too tightly to any particular language server. If RLS manages to leapfrog Rust Analyzer, or something else comes along and gains adoption in the Rust community, I'd want to primarily use that language server. For these reasons, I though it wise to keep the name for the extension generic.

Both Nova and GitHub use project descriptions in search results, so I'm hoping that now including Rust Analyzer in descriptions for both the extension and this project will make it more discoverable for people specifically interested in Rust Analyzer. Thanks for bringing up this issue!

**Comment by laralove143** [comment]
there's already an extension with the exact same name though- idk if nova would even allow that

**Comment by kilbd** [comment]
Yep, the only field that needs to be unique is `identifier`. There are competing extensions in Nova with the same name – Deno comes to mind.

I targeted this extension at the same users as the existing extension, but with a few key benefits:
* more reliable - uses a language server that better supports the LSP spec, issues stay in sync, etc.
* richer syntax definitions for improved highlighting
* formats on save rather than on command
* most importantly, has maintainers interested in continuing to improve the extension and support improvements to Rust and Nova. For any number of good reasons, the existing extension has been stale for too long, and I wanted to show Rustaceans who enjoy Nova as much as I do some love. 🦀❤️

**Comment by laralove143** [comment]
that's exactly why i think it should have a different name, not necessarily Rust Analyzer. like say you have to recommend it to someone, you have to say x's Rust extension instead of just the extension's name. another solution would be to contact the existing extension's maintainer and ask them to archive it or something. also these features should definitely be mentioned in the Readme

**Comment by kilbd** [comment]
Yeah, I agree that it could cause some confusion. I suppose what I like about naming it simply "Rust" is how it communicates that it is an authoritative resource for Rust projects, particularly for users new to Nova. I intend for this project to better live up to the promise of being authoritative and I didn't want to diminish it by adding any kind of qualifier.

I could see "__Rust Lang__" being a good option or maybe the full "__Rust Language__" (though I prefer brevity). I'll keep chewing on it. Naming is hard!

Thanks for continuing to discuss this issue with me!

**Comment by laralove143** [comment]
of course! i don’t think rust analyzer is very descriptive either tbh. after all it includes clippy/check and rustfmt support. maybe something less formal like “Not Enough Rust” just an idea

**Comment by kilbd** [comment]
You may have seen I reverted back to "Rust" for the name. I tried on a lot of other names, but "Rust" still felt like it fit the best. For now, I'm going to hope that people will be able to tell the difference between extensions. When I get this extension a bit more stabilized, I'll reach out to the developer of the other extension and see if he's willing to add a note to his extension that it is no longer under active development (as appears to be the case).
