### ISSUE TITLE
[BUG] The symbols fold slider doesn't unfold

### ISSUE THREAD

**Issue by laralove143** [kilbd/nova-rust#40]
**Describe the bug**
Normally, the slider should fold everything when it's at the left, and unfold when it's at the right. The bug happens when you move the slider to right, then back to left. Moving it to the right unfolds it but moving it to the left doesn't seem to do anything.

**To Reproduce**
1. Symbols in the left sidebar at the bottom by default
2. Make sure it's on _Hierarchical_
3. Move the slider under _Hierarchical_ to the right
4. Move it back  to the left
5. The symbols aren't folded

**Expected behavior**
The symbols are folded back.

**Screenshots**
https://user-images.githubusercontent.com/82576556/230971865-6472e5f1-1fb1-469f-bd74-32bcdfbf250f.mov

**Versions (please complete the following information):**
 - macOS: Ventura
 - Processor: Air M1
 - Nova: 10.6
 - Extension Version: 2.3.1

**Comment by kilbd** [comment]
Nova does the same thing when I look at a TypeScript file, so I'm guessing this is a Nova bug. I filed [a bug report](https://devforum.nova.app/t/symbols-sidebar-not-collapsing/2067) with Panic so hopefully they'll address it soon!

**Comment by kilbd** [comment]
Panic reports that this is fixed in Nova 11, which is in beta and due soon!
